repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.72.0
    hooks:
      - id: semgrep
        args: [--config=.semgrep.yml]
        types: [python, javascript]  # Явное указание
        additional_dependencies: [semgrep==1.72.0]