# .semgrep.yml

# Основные правила сканирования
rules:
  # 1. Используем встроенные правила безопасности OWASP Top 10
  - id: owasp-rules
    pattern: p/owasp-top-ten
    message: "OWASP Top 10 Security Checks"
    languages: [php, javascript]
    severity: WARNING

  # 2. Кастомные правила для bWAPP (убедитесь что файл существует)
  - id: bwapp-custom-rules
    pattern: file:custom_rules.yml
    message: "Custom bWAPP Security Rules"
    languages: [php]
    severity: ERROR

# Настройки исключений
exclude:
  - "**/tests/**"
  - "**/vendor/**"
  - "**/node_modules/**"
  - "**/docs/**"

# Настройки вывода
output:
  format: sarif  # Формат для интеграции с GitHub/GitLab
  sarif:
    omit-irrelevant: true

# Дополнительные опции
verbose: true    # Подробный вывод
strict: true     # Строгая проверка