name: Security Scanning
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Еженедельно в воскресенье

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # SAST - Semgrep
    - name: Run Semgrep (SAST)
      uses: returntocorp/semgrep-action@v1
      with:
        config: .semgrep.yml
        output_file: sast_report.sarif

    # IAC - Checkov
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        output_format: sarif
        output_file: iac_report.sarif
        skip_check: CKV_DOCKER_3,CKV_DOCKER_8  # Пропуск нерелевантных проверок

    # DAST - OWASP ZAP (базовое сканирование)
    - name: OWASP ZAP Scan
      run: |
        docker run --network host -v $(pwd):/zap/wrk \
          owasp/zap2docker-stable zap-baseline.py \
          -t http://localhost \
          -r dast_report.html \
          -I  # Игнорировать предупреждения о неработающих правилах
    # Container Scan - Docker Scout
    - name: Docker Scout Analysis
      run: |
        docker pull raesene/bwapp
        docker scout cves raesene/bwapp \
          --format sarif \
          --output docker_report.sarif
    # Загрузка отчётов
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          *.sarif
          dast_report.html
        retention-days: 7
