name: Security Scanning
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Еженедельно в воскресенье в 00:00 UTC

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write  # Для загрузки результатов в Code Scanning
      contents: read         # Для доступа к коду репозитория

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Для полной истории коммитов (может потребоваться для некоторых сканеров)

    # SAST - Semgrep
    - name: Run Semgrep (SAST)
      uses: returntocorp/semgrep-action@v1
      with:
        config: .semgrep.yml
        output_file: sast_report.sarif
        severity: ERROR  # Минимальный уровень серьезности
        force_color: true  # Добавлено: цветной вывод в логах

    # IAC - Checkov
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        output_format: sarif
        output_file: iac_report.sarif
        skip_check: CKV_DOCKER_3,CKV_DOCKER_8
        soft_fail: true  # Продолжить workflow даже при нахождении проблем
        quiet: true      # Добавлено: уменьшает вывод в логах

    # Container Scan - Docker Scout
    - name: Docker Scout Analysis
      timeout-minutes: 10  # Добавлено: ограничение времени выполнения
      run: |
        docker pull raesene/bwapp
        docker scout cves raesene/bwapp \
          --format sarif \
          --output docker_report.sarif \
          --exit-code 0  # Продолжить workflow даже при нахождении уязвимостей

    # Загрузка отчётов
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          sast_report.sarif
          iac_report.sarif
          docker_report.sarif
          dast_report.html  # Убедитесь, что этот файл создается
        retention-days: 7
        if-no-files-found: warn  # Добавлено: предупреждение вместо ошибки

    # Отправка в GitHub Code Scanning
    - name: Upload SARIF to Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: |
          sast_report.sarif
          iac_report.sarif
          docker_report.sarif
        category: security-scan  # Добавлено: категория для результатов